<?php

return [
    [
        'id' => 'ST-2025-001',
        'submitted_at' => '2025-01-12T08:30:00+07:00',
        'letter_number' => '001/SPP-ST/I/2025',
        'event_start' => '2025-01-18',
        'event_end' => '2025-01-20',
        'activity_name' => 'Pendampingan Transparansi Data Pemerintah Kota',
        'client_name' => 'Bank Mandiri',
        'activity_type' => 'offline',
        'pics' => [
            ['name' => 'Rahmat Hidayat', 'role' => 'Lead PIC'],
            ['name' => 'Mira Puspita', 'role' => 'Koordinator Lapangan'],
        ],
        'companion_name' => 'Dewi Lestari',
        'companion_fee' => 1_250_000,
        'instructors' => [
            ['name' => 'Agus Wibowo', 'fee' => 1_500_000],
            ['name' => 'Siti Ramadhani', 'fee' => 1_350_000],
        ],
        'status' => 'Menunggu Persetujuan',
        'status_note' => 'Menunggu tanda tangan Kepala Bagian.',
        'created_by' => 'Rahmat Hidayat',
        'status_updated_by' => 'Putri Saraswati',
        'status_updated_at' => '2025-01-13T10:05:00+07:00',
    ],
    [
        'id' => 'ST-2025-002',
        'submitted_at' => '2025-01-09T14:15:00+07:00',
        'letter_number' => '002/SPP-ST/I/2025',
        'event_start' => '2025-01-22',
        'event_end' => '2025-01-22',
        'activity_name' => 'Sosialisasi Layanan SPP Online',
        'client_name' => 'Bank Syariah Indonesia',
        'activity_type' => 'online',
        'pics' => [
            ['name' => 'Sari Wulandari', 'role' => 'PIC Utama'],
            ['name' => 'Ario Nugroho', 'role' => 'Moderator Webinar'],
        ],
        'companion_name' => 'Ridwan Pratama',
        'companion_fee' => 0,
        'instructors' => [
            ['name' => 'Mikael Santoso', 'fee' => 900_000],
        ],
        'status' => 'Disetujui',
        'status_note' => 'Surat telah disahkan oleh pimpinan.',
        'created_by' => 'Sari Wulandari',
        'status_updated_by' => 'Budi Hartono',
        'status_updated_at' => '2025-01-10T09:20:00+07:00',
    ],
    [
        'id' => 'ST-2025-003',
        'submitted_at' => '2025-01-05T09:45:00+07:00',
        'letter_number' => '003/SPP-ST/I/2025',
        'event_start' => '2025-01-25',
        'event_end' => '2025-01-27',
        'activity_name' => 'Workshop Transformasi Digital Regional',
        'client_name' => 'Bank Negara Indonesia',
        'activity_type' => 'offline',
        'pics' => [
            ['name' => 'Rangga Saputra', 'role' => null],
        ],
        'companion_name' => null,
        'companion_fee' => null,
        'instructors' => [
            ['name' => 'Nurul Hidayah', 'fee' => 1_250_000],
            ['name' => 'Bima Prakoso', 'fee' => 1_250_000],
            ['name' => 'Yuni Astuti', 'fee' => 1_100_000],
        ],
        'status' => 'Revisi',
        'status_note' => 'Lengkapi daftar peserta dan agenda final.',
        'created_by' => 'Rangga Saputra',
        'status_updated_by' => 'Nur Aisyah',
        'status_updated_at' => '2025-01-08T16:40:00+07:00',
    ],
];
